export {default as HomeHeader} from './components/home-header/HomeHeader'
export {default as HomeConcept} from './components/home-concept/HomeConcept'
export {default as HomeDinosaur} from './components/home-dinosaur/HomeDinosaur'
export {default as HomeFooter} from './components/home-footer/HomeFooter'
export {default as HomeEras} from './components/home-eras/HomeEras'
export {default as HomePaleontology} from './components/home-paleontogy/HomePaleontology'